apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
      - name: brain-tasks-app
        image: 043206426566.dkr.ecr.ap-south-1.amazonaws.com/project1-ecr-repo
        ports:
        - containerPort: 3000
