apiVersion: v1 
kind: Service
metadata:
  name: brain-tasks-app-service
spec:
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer